languageCode = "en"
languageName = "English"
weight = 1
title = ""

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2006-01-02"
  logo = "img/LogoDarkTheme.png"
  secondaryLogo = "img/LogoLightTheme.png"
  description = "Wei Yi Chung's Developer Blog"

[params.author]
  name = "Wei Yi Chung"
  email = "hwork0511@gmail.com"
  image = "img/Profile.jpeg"
  headline = "Software Engineer @AICS"
  bio = "Working at the contributing of open source, distributed systems, and data engineering."
  links = [
    { github = "https://github.com/h30306" },
    { linkedin = "https://www.linkedin.com/in/howard-w-chung/" },
    { email = "mailto:hwork0511@gmail.com" },
    { graduation-cap = "https://scholar.google.com/citations?user=ipNRv6gAAAAJ" },
  ]