# config/_default/menus.toml

[[main]]
  name = "Blog"
  pageRef = "tags/blog"
  weight = 10

[[main]]
  name = "Categories"
  pageRef = "categories"
  weight = 20

# Sub Menu for Categories
[[main]]
  name = "Algorithm"
  parent = "Categories"
  pageRef = "tags/algorithm"
  weight = 22

[[main]]
  name = "Backend"
  parent = "Categories"
  pageRef = "tags/backend"
  weight = 24

[[main]]
  name = "Database"
  parent = "Categories"
  pageRef = "tags/database"
  weight = 26

[[main]]
  name = "DistributionSystem"
  parent = "Categories"
  pageRef = "tags/distribution-system"
  weight = 28

[[main]]
  name = "Interview"
  parent = "Categories"
  pageRef = "tags/interview"
  weight = 30

[[main]]
  name = "Internship"
  parent = "Categories"
  pageRef = "tags/intern"
  weight = 32

[[main]]
  name = "LeetCode"
  parent = "Categories"
  pageRef = "tags/leetcode"
  weight = 34

[[main]]
  name = "Paper"
  parent = "Categories"
  pageRef = "tags/paper"
  weight = 36

[[main]]
  name = "Tags"
  parent = "Categories"
  pageRef = "tags"
  weight = 38

[[main]]
  pre = "github"
  identifier = "github"
  url = "https://github.com/h30306"
  weight = 40

[[main]]
  pre = "linkedin"
  identifier = "linkedin"
  url = "https://www.linkedin.com/in/howard-w-chung"
  weight = 50
